apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patch-configmap.yaml
  - path: patch-replicas.yaml
  - path: patch-ingress.yaml

images:
  - name: ghcr.io/jeonchulho/msg_server
    newTag: latest
