apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: msg-server
  namespace: msg
spec:
  rules:
    - host: chat.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chat
                port:
                  number: 8080
    - host: session.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: session
                port:
                  number: 8090
    - host: orghub.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: orghub
                port:
                  number: 8091
    - host: tenanthub.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tenanthub
                port:
                  number: 8092
    - host: fileman.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fileman
                port:
                  number: 8081
