apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: chat
  namespace: msg
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chat
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: session
  namespace: msg
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: session
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: orghub
  namespace: msg
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: orghub
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tenanthub
  namespace: msg
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tenanthub
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fileman
  namespace: msg
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fileman
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dbman
  namespace: msg
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dbman
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
