apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.example.yaml
  - chat.yaml
  - orghub.yaml
  - tenanthub.yaml
  - session.yaml
  - fileman.yaml
  - dbman.yaml
  - pdb.yaml
  - vectorman.yaml
  - ingress.yaml
  - hpa.yaml
