apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: msg-server
  namespace: msg
spec:
  rules:
    - host: dev-chat.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chat
                port:
                  number: 8080
    - host: dev-session.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: session
                port:
                  number: 8090
    - host: dev-orghub.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: orghub
                port:
                  number: 8091
    - host: dev-tenanthub.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tenanthub
                port:
                  number: 8092
    - host: dev-fileman.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fileman
                port:
                  number: 8081
