apiVersion: v1
kind: ConfigMap
metadata:
  name: msg-server-config
  namespace: msg
data:
  APP_ENV: "staging"
  MILVUS_ENABLED: "true"
  DBMAN_HTTP_TIMEOUT_MS: "2500"
  DBMAN_FAIL_THRESHOLD: "2"
  DBMAN_COOLDOWN_MS: "3000"
