apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: msg-server
  namespace: msg
spec:
  rules:
    - host: staging-chat.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chat
                port:
                  number: 8080
    - host: staging-session.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: session
                port:
                  number: 8090
    - host: staging-fileman.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fileman
                port:
                  number: 8081
